language: generic
install:
- yarn install
script:
- yarn build
after_script:
- rm -rf node_modules
- tar cvf build.tar.gz .
- curl -H "X-Token:$_token" -H "X-Repo:portfolio" -F build=@build.tar.gz https://gomasy.jp/deploy
addons:
  apt:
    update: true
notifications:
  slack:
    secure: fOYrRTXFM0g9Qw/uo3FTBanRCfb+LrSh2iYFQNqpCvDqDJLITUdtkGHLUVMl1R2vapdV4G0O6e9zacCEPwCdtMZDdbfT4Wky6ap9SEfJh4AsDbcoQL30H2nOAu9B8hPTLobmMRyLJWAlDwA6od11qdVSIWWkOCGv7MVka8SzmJ0=
