language: generic
install:
- yarn install
script:
- yarn build
after_script:
- tar cvf build.tar.gz .
- curl -H "X-Token:$_token" -H "X-Repo:portfolio" -F build=@build.tar.gz https://gomasy.jp/deploy
addons:
  apt:
    update: true
