name: CD workflow
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --pure-lockfile
    - name: Run build
      env:
        NODE_OPTIONS: --openssl-legacy-provider
      run: yarn build
    - name: Run deploy
      if: github.ref == 'refs/heads/master'
      env:
        _TOKEN: ${{ secrets._TOKEN }}
      run: |
        tar --exclude "node_modules" --exclude ".git*" -cf build.tar.gz .
        curl -H "X-Token:$_TOKEN" -H "X-Repo:portfolio" -F build=@build.tar.gz https://gomasy.jp/api/v1/github/push
    - name: Post a message in a channel
      uses: slackapi/slack-github-action@v2
      if: github.ref == 'refs/heads/master'
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          channel: "${{ secrets.SLACK_CHANNEL }}"
          username: "GitHub Actions"
          icon_emoji: ":gear:"
          text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
